#! /usr/bin/env python

from gi.repository import GLib
import pydbus
import coiot.dbus
import bluez
from coiot.device import CoiotDevice
from coiot.db import CoiotDB
from ble.client import BleClient
import logging

if __name__ == "__main__":
    for logn in 'DB', 'DBus', 'Device', 'BLE':
        logging.getLogger(logn).level = logging.DEBUG

    db = CoiotDB('/tmp/coiot.db')
    dev = db.install()
    dev.install_interface(coiot.db.Switchable, On=False)
    dev.install_interface(coiot.driver.BLEDriverParameters,
                          Mac="00:00:00:00:00:00")

    adapter = bluez.DBusBluez().adapters['hci0']
    client = BleClient(adapter)
    driver = bluez.BluezBLEDriver(client)

    updates = set()
    CoiotDevice.load(db, updates.add)

    def idle_push_updates():
        while updates:
            d = updates.pop()
            d.update()
        return True

    coiot.dbus.CoiotDBus(pydbus.SystemBus())

    loop = GLib.MainLoop()
    GLib.idle_add(idle_push_updates)
    loop.run()
