#! /usr/bin/sh
cd "$(dirname $(readlink -f $0))"

source ./generic_check.sh

tr=0

run_check_script "unit tests" ./check_unit_test
tr=$(($tr | $?))
run_check_script "syntax check" ./check_syntax
tr=$(($tr | $?))

exit $tr
