#! /usr/bin/bash
cd "$(dirname "$(readlink -f "$0")")" || exit 2

source ./generic_check.sh

tr=0
echo "git diff --color=always --exit-code" | run_check_pipe "git diff"
tr=$((tr | $?))

echo "git diff --color=always --cached --exit-code" | run_check_pipe "git cached diff"
tr=$((tr | $?))
exit $tr
